version: '3'

services:
  
  service-rabbitmq:
    container_name: container-rabbitmq
    image: 'rabbitmq:3.10.0-management-alpine'
    ports:
      - "5672:5672" # The standard AMQP protocol port
      - "15672:15672" # HTTP management UI
    volumes:
      - .docker/rabbitmq/data/:/var/lib/rabbitmq/
      - .docker/rabbitmq/log/:/var/log/rabbitmq  
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    networks:
      - network
      
  service-report-api:
    container_name: report-api-app
    image: report-api-app:latest
    build:
      context: ./report-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    entrypoint: ./entrypoint.sh
    env_file:
      - ./report-api/.env
    environment:
      AMQP_SERVER_URL: amqp://guest:guest@container-rabbitmq:5672/  
    depends_on:
      - service-rabbitmq
    networks:
      - network
      
  service-report-consumer:
    container_name: report-consumer-app
    image: report-consumer-app:latest
    build:
      context: ./report-consumer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ENV: docker
    entrypoint: /opt/bin/entrypoint.sh
    depends_on:
      - service-rabbitmq
    networks:
      - network

  service-report-web:
    container_name: report-web-app
    image: report-web-app:latest
    build: 
        context: ./report-web
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./report-web/.env    
    command: npm run start
    depends_on:
      - service-report-api    
    networks:
      - network    
      
networks:
  network: {}