server:
  port: 8080
spring:    
 rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: app.log