server:
  port: 8080
spring:    
 datasource:
   url: jdbc:h2:mem:localhost/test
   username: sa
   password: sa
 liquibase:
  change-log: classpath:/db/changelog/changelog-master.xml     
 h2:
   console:
     enabled: true
 rabbitmq:
   host: localhost
   port: 5672
   username: guest
   password: guest
 jpa:
   properties:
     hibernate:
       dialect: org.hibernate.dialect.H2Dialect
       ddl-auto: update          
 mail: 
   host: smtp.ethereal.email
   port: 587
   username: brooklyn49@ethereal.email
   password: Gp66dd5QfXWNkU7qGe
   properties:
     mail:
       transport:
         protocol: smtp
       smtp:
         auth: true
         starttls:
           enable: true
           required: true
         ssl:
           enabled: true
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
   name: app.log
   
#https://ethereal.email/create ==== config email
#https://ethereal.email/messages == verifique o e-mail enviado aqui